### PR TITLE
Release v3.0.0

### PR DESCRIPTION
**Pull request by forrestfwilliams**
This is the first of several major refactoring efforts for this repository. In this release we are removing all functionality not being used internally at ASF and getting the repository up to our current formatting and CI/CD standards. Expect another major release that will further migrate some functionality and perform some breaking refactoring changes.

### CODE REVIEW

**Review by jhkennedy — CHANGES_REQUESTED** [review]
Looks good, but we should at least clean up the python version stuff -- either testing all supported versions or dropping support for the untested versions.

I also added some other thoughts that don't need to be addressed here necessarily.

**Comment by jhkennedy** [comment]
I opened #294 to clean up the Python version stuff, which should resolve all my requested changes.

**Review by jhkennedy — APPROVED** [review]

**Comment by jhkennedy** [comment]
Confirmed this version of hyp3lib works in hyp3-isce2, so I think we are g2g to move forward.

**Comment by forrestfwilliams** [comment]
🎉

**Pull request merged**
